[program:surprisemoi-scheduler]
process_name=%(program_name)s
command=docker exec -u www-data surprisemoi-app php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deploy
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/surprise_moi/storage/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=60
